Repository cdktf/cdktf-local-exec, pull requests merged in 2023-08, with the labels that each got.

#163 chore(deps): upgrade dependencies
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#164 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#165 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#167 feat: upgrade to jsii v5.1.x
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: auto-approve, automerge

#169 chore!: upgrade to cdktf 0.18.0
  .github/workflows/upgrade-cdktf.yml
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  projenrc/upgrade-cdktf.ts
  yarn.lock
Labels: auto-approve, automerge, dependencies

#170 chore(ci): fix links in upgrade script
  .github/workflows/upgrade-cdktf.yml
  projenrc/upgrade-cdktf.ts
Labels: auto-approve, automerge

#171 chore: remove default pull request template
  .gitattributes
  .github/pull_request_template.md
  .gitignore
  .projen/files.json
  .projenrc.ts
Labels: auto-approve, automerge

#172 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, automerge, dependencies
