Repository cdktf/cdktf-local-exec, pull requests merged in 2023-05, with the labels that each got.

#130 fix: make auto-approve actually work
  .github/workflows/auto-approve.yml
  .github/workflows/upgrade-main.yml
  .projenrc.ts
Labels: automerge

#125 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#131 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#132 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, dependencies

#133 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#134 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#135 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#136 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#137 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#138 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, dependencies
